# version: 2.1
# orbs:
#   node: circleci/node@1.1
# jobs:
#   build:
#     excutor:
#       name: node/default
#       tag: '10.4'
#     steps:
#       - checkout
#       - node/with-cache:
#         steps:
#           - run: npm install
#       - run: npm run test

version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test